# # require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '11.0'

# target 'kepah_security_32637' do
#   config = use_native_modules!


#   pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
#   pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
#   pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
#   pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
#   pod 'React', :path => '../node_modules/react-native/'
#   pod 'React-Core', :path => '../node_modules/react-native/'
#   pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
#   pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
#   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

#   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#   pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
#   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
#   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

#   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

#   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#   # use_react_native!(
#   #   :path => config[:reactNativePath],
#   #   # to enable hermes on iOS, change `false` to `true` and then install pods
#   #   :hermes_enabled => false
#   # )

#   target 'kepah_security_32637Tests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   use_native_modules!

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable the next line.
#   # use_flipper!()

#   post_install do |installer|
#     react_native_post_install(installer)
#   end
# end



source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
def add_flipper_pods!
  version = '~> 0.93.0'
  pod 'FlipperKit', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
        # if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        # endØ
      end
    end
  end


  # installer.pods_project.targets.each do |target|
  #   target.build_configurations.each do |config|

  #   end
  # end


end

target 'kepah_security_32637' do
  # Pods for kepah_security_32637
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'kepah_security_32637Tests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)

    ## Fix for XCode 12.5
    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
    find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
    "RCTBridgeModuleNameForClass(strongModule))", "RCTBridgeModuleNameForClass(Class(strongModule)))")
  end

  def find_and_replace(dir, findstr, replacestr)
    Dir[dir].each do |name|
        text = File.read(name)
        replace = text.gsub(findstr,replacestr)
        if text != replace
            puts "Fix: " + name
            File.open(name, "w") { |file| file.puts replace }
            STDOUT.flush
        end
    end
    Dir[dir + '*/'].each(&method(:find_and_replace))
  end
  
end

# target 'kepah_security_32637-tvOS' do
#   # Pods for kepah_security_32637-tvOS

#   target 'kepah_security_32637-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
